openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Bindings for Pulp Ansible API
  license:
    name: Apache-2.0

paths:
  # Pulp Collections API
  "/pulp/api/v3/content/ansible/collection_versions/":
    get:
      operationId: "list"
      tags: ["pulp: collections"]
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: namespace
          schema:
            type: string
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: version
          schema:
            type: string
        - in: query
          name: is_highest
          schema:
            type: boolean
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: fields
          schema:
            type: string
        - in: query
          name: exclude_fields
          schema:
            type: string
        - in: query
          name: tags
          schema:
            type: string
        - in: query
          name: certification
          schema:
            type: string
        - in: query
          name: ordering
          schema:
            type: string
        - in: query
          name: deprecated
          schema:
            type: boolean

      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsPage'

  "/pulp/api/v3/content/ansible/collection_versions/{id}/":
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      operationId: "get"
      tags: ["pulp: collections"]
      security:
        - BasicAuth: []
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object

  # Pulp Tags API
  "/pulp/api/v3/pulp_ansible/tags/":
    get:
      operationId: "list"
      tags: ["pulp: tags"]
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsPage'


  # Galaxy Collections API
  "/{prefix}/v3/collections/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
    get:
      operationId: "list"
      tags: ["galaxy: collections"]
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsPage'

  "/{prefix}/v3/collections/{namespace}/{name}/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
      - in: path
        name: namespace
        required: true
        schema:
          type: string
      - in: path
        name: name
        required: true
        schema:
          type: string
    get:
      operationId: "get"
      tags: ["galaxy: collections"]
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: "put"
      tags: ["galaxy: collections"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collection'
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'

  # Galaxy Collection Versions API
  "/{prefix}/v3/collections/{namespace}/{name}/versions/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
      - in: path
        name: namespace
        required: true
        schema:
          type: string
      - in: path
        name: name
        required: true
        schema:
          type: string
    get:
      operationId: "list"
      tags: ["galaxy: collection versions"]
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: certification
          schema:
            type: string
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsPage'

  "/{prefix}/v3/collections/{namespace}/{name}/versions/{version}/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
      - in: path
        name: namespace
        required: true
        schema:
          type: string
      - in: path
        name: name
        required: true
        schema:
          type: string
      - in: path
        name: version
        required: true
        schema:
          type: string
    get:
      operationId: "get"
      tags: ["galaxy: collection versions"]
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object

  "/{prefix}/v3/collections/{namespace}/{name}/versions/{version}/certified/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
      - in: path
        name: namespace
        required: true
        schema:
          type: string
      - in: path
        name: name
        required: true
        schema:
          type: string
      - in: path
        name: version
        required: true
        schema:
          type: string
    put:
      operationId: "set_certified"
      tags: ["galaxy: collection versions"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificationInfo'
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object

  # Galaxy Artifacts API
  "/{prefix}/v3/artifacts/collections/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
    post:
      operationId: upload
      tags: ["galaxy: artifacts"]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                sha256:
                  type: string
                expected_namespace:
                  type: string
                expected_name:
                  type: string
                expected_version:
                  type: string
              required:
                - file
      responses:
        202:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  task:
                    type: string
                    format: uri

  # Galaxy Imports API
  "/{prefix}/v3/imports/collections/{id}/":
    parameters:
      - in: path
        name: prefix
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      operationId: "get"
      tags: ["galaxy: imports"]
      security:
        - BasicAuth: []
      responses:
        202:
          description: "Accepted"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionImport'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    ResultsPage:
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
          format: uri
        previous:
          type: string
          format: url
        results:
          type: array
          items:
            type: object

    Collection:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
        deprecated:
          type: boolean

    CollectionImport:
      type: object
      properties:
        id:
          type: string
        state:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        started_at:
          type: string
          format: date-time
        finished_at:
          type: string
          format: date-time
        error:
          type: object
        messages:
          type: array
          items: {}

    CertificationInfo:
      type: object
      required:
        - certification
      properties:
        certification:
          type: string
